
#ifndef IMAGE_TRANSFORMER_EXIT_CODES_H
#define IMAGE_TRANSFORMER_EXIT_CODES_H

#define WRONG_ARGUMENTS_EXIT_CODE 1
#define FILE_DOESNT_EXISTS_EXIT_CODE 2
#define READ_ERROR_EXIT_CODE 3
#define WRITE_ERROR_EXIT_CODE 4
#define OUT_OF_MEMORY_EXIT_CODE 5

#endif //IMAGE_TRANSFORMER_EXIT_CODES_H